### ISSUE TITLE
Add Documentation 

### ISSUE THREAD

**Issue by PatAKnight** [janus-idp/backstage-showcase#10]
Story
- As a developer, I would like to better understand the purpose of the Backstage Showcase app.

Description
- We should expanded up our documentation to allow members of the community to better understand the Backstage Showcase app. This should include information on contributing to the project (creating issues, pull requests), an updated README (outlining the purpose of the app and links to additional documentation), how to get started with the app, and more.

AC
- Updated README to explain the purpose of the app
- Contribution documentation

Additional Notes
- This will need more refinement to better capture what all we will be looking for.

**Comment by christophe-f** [comment]
With the documentation available in the README, is it good to close?
