### ISSUE TITLE
Improve our system of tagging images

### ISSUE THREAD

**Issue by PatAKnight** [janus-idp/backstage-showcase#102]
### What do you want to improve?
We have some interest coming in from other teams to use the images that we build for the backstage-showcase app. We should come up with a method for improving how we tag our images to ensure that we do not introduce a breaking change / error that could potentially be disruptive to the other teams.
### What is the current behavior?
We create two images that are tagged with latest and the git id every time there is a push to main.
### What is the new behavior?
A method of ensuring there is an image that we can guarantee will work for the other teams. A couple of ideas that come to mind are included below.

- Start a versioning system where we have major versions that we can guarantee will work and minor versions that could introduce an issue / error and tag accordingly
- Pull and re-tag the previous git id tagged images to something that will be identifiable to the other teams
- Keeping track of previous git id tags that we know work and updating teams when new ones arrive

### :warning: Is this a breaking change?

_Put an `x` in the boxes that apply_

- [ ] Yes
- [x] No
- [ ] Don't know

**Comment by schultzp2020** [comment]
We should use [changesets](https://www.npmjs.com/package/@changesets/cli) and then use the changeset when tagging images.
