### ISSUE TITLE
Enable github org processor

### ISSUE THREAD

**Issue by raffaelespazzoli** [janus-idp/backstage-showcase#115]
### What do you want to improve?

Enable the github org processor, to automatically import developers and groups from github org members and github org teams.
 Please refer to this document: https://backstage.io/docs/integrations/github/org

### :warning: Is this a breaking change?

_Put an `x` in the boxes that apply_

- [ ] Yes
- [ ] No
- [x] Don't know

**Comment by christophe-f** [comment]
We can enable this temporarily but this is part of a larger topic.
