### ISSUE TITLE
Enable github identity resolver

### ISSUE THREAD

**Issue by raffaelespazzoli** [janus-idp/backstage-showcase#116]
### What do you want to improve?

Enable github identity resolver, this will allow a user that logs in to be mapped to an identity imported via the github org processor (see #115 ). This is a necessary step to understand the ownership of a user that is logged it. Having an identity resolver is also the base of any serious RBAC implementation.

see here: https://backstage.io/docs/auth/identity-resolver/#built-in-resolvers
also an implementation with the default github idneityt resolver: https://github.com/raf-backstage-demo/backstage-app-demo/blob/main/packages/backend/src/plugins/auth.ts

### :warning: Is this a breaking change?

_Put an `x` in the boxes that apply_

- [ ] Yes
- [ ] No
- [x] Don't know

**Comment by christophe-f** [comment]
Let's add the GitHub one for now. We will need to create an epic for the other providers
