### ISSUE TITLE
Unable to log in using GitHub

### ISSUE THREAD

**Issue by PatAKnight** [janus-idp/backstage-showcase#127]
### What happened?
There is an issue where we are unable to log in via GitHub within the showcase app. This is leading to most of the GitHub plugins being unavailable.
### What are the steps to reproduce this issue?

1. Navigate to the showcase app
2. Go to the catalog
3. Select backstage-showcase
4. Attempt to log in
5. See “User not found”

### Browser affected

_Put an `x` in the boxes that apply_

- [ ] All
- [x] Chrome
- [ ] Safari
- [ ] Edge
- [ ] Firefox

We only support the last 2 major versions.

### Devices affected

_Put an `x` in the boxes that apply_

- [ ] All
- [x] Desktop
- [ ] Tablet
- [ ] Phone

Attach any related screenshots, if any.

**Comment by PatAKnight** [comment]
Fixed by #129. Leaving open to see if we can still implement the original idea

**Comment by kadel** [comment]
>Fixed by https://github.com/janus-idp/backstage-showcase/pull/129. Leaving open to see if we can still implement the original idea
