### ISSUE TITLE
turbo configuration issue when creating a new back-end plugin 

### ISSUE THREAD

**Issue by 04kash** [janus-idp/backstage-showcase#1270]
### Describe the bug

On creating a backend plugin with a `dev/index.ts` file present in it and running `yarn start` in the root directory, both the backend in `packages/backend/index.ts` and in the backend plugin's `dev/index.ts` run.
This issue does not appear with existing plugins as shown in the screenshot as they don't have a `dev/index.ts` file:

![Screenshot from 2024-05-21 15-56-22](https://github.com/janus-idp/backstage-showcase/assets/113269381/f02facce-c36f-4bff-b2b6-d3caa4fa1920)

### Expected Behavior
`yarn start` in the root directory  runs without any errors

### What are the steps to reproduce this bug?

1. run yarn new --select backend-plugin  (named it hello)
2. run yarn --cwd packages/backend add @internal/backstage-plugin-hello-backend@^0.1.0
3. add backend.add(import('@internal/backstage-plugin-hello-backend')); to packages/backend/index.js
4. run yarn start

### Versions of software used and environment
Built on top of commit [4cf349cd4bb17a1ec13b7d6d64c6f1492fbf028b](https://github.com/janus-idp/backstage-showcase/tree/4cf349cd4bb17a1ec13b7d6d64c6f1492fbf028b) of `backstage-showcase`

**Comment by Zaperex** [comment]
For context, this causes port 7007 to be used by both, and typically caused the backstage-showcase `backend` to fail since the other plugin already grabbed port 7007.
