### ISSUE TITLE
Improve build time

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#130]
## Goal
The build used to take around 10 minutes which is a long time. It now takes at least 20 minutes. The goal is to optimize the build  and reduce it to only 2-3 minutes.

## Acceptance criteria
- [ ] Showcase built should take only 2-3 minutes.

## Issues in Epic
- [x] #131 
- [x] #132 
- [x] #55 
- [x] #133 
- [x] #139

**Comment by rtaniwa** [comment]
This looks complete as all the child stories are done so I am closing.
