### ISSUE TITLE
Fix the Publish TechDocs Site GitHub Action

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#138]
### What happened?

When the CLI is trying to publish the content, the GH action returns:
`error: required option '--entity <NAMESPACE/KIND/NAME>' not specified`

### What are the steps to reproduce this issue?

1. Trigger the GitHub action
2. Wait about 40 seconds
3. Check the logs

**Comment by SamoKopecky** [comment]
I can have a look at this.
