### ISSUE TITLE
Add more plugins to the Showcase app

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#167]
## Goal

Each user of the Showcase image will use different tools. Gitlab CI/GH Action/Jekins, or Jira/GH issues orGH/Bitbucket/Gitlab, etc Janus Showcase need to work with all the common tools.

## Acceptance criteria

- [ ] tdb

## Requirements

- [ ] Plugin
- [ ] Test plan
- [ ] Installation documentation
- [ ] End user documentation

### Phase 1
- [x] #168 
- [x] #171
- [x] #172
- [x] #173
- [x] #174
- [x] #175 
- [x] #176 

### Phase 2
- [x] #169
- [x] #170
- [x] #177 

## Notes

**Additional context**
For most of the plugin we need to install the frontend (sometimes the backend plugin), add the `proxy` settings in the `app-config.yaml`, make sure that the URL+tokens can be parameterized, and that the Getting Started documentation is updated.

**Comment by rtaniwa** [comment]
All child issues are closed, so I am closing this issue.
