### ISSUE TITLE
Add Dynatrace plugin

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#169]
### Acceptance criteria

We need to add the [Dynatrace plugin](https://github.com/backstage/backstage/tree/master/plugins/dynatrace). 

The Dynatrace card should be added to a new 'Monitoring' tab in the Entity page (if does not exists) and wrapped with the conditional `isDynatraceAvailable ` flag.

**Comment by Zaperex** [comment]
The [Dynatrace plugin ](https://github.com/backstage/backstage/tree/master/plugins/dynatrace) appears to require additional API token permissions (either `DataExport`, `ExternalSyntheticIntegration` or `ReadSyntheticData`) which is not documented in the plugin documentation. 

Additionally it appears that the "View Entity in Dynatrace ->" button under the problems list component does not link to a valid page.
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/51682e48-01fd-4498-835b-04147e09442f)
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/d8ec5737-aa84-44fd-9822-12044734894e)
