### ISSUE TITLE
OpenShift Learning Path *plugin*

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-showcase#211]
Create a new page in the Showcase top level navigation that displays following content:

Source data from:
https://github.com/janus-idp/backstage-showcase/blob/main/packages/app/public/homepage/data.json

See examples how it's currently consumed at:
https://github.com/janus-idp/backstage-showcase/blob/main/packages/app/src/components/home/HomePage.tsx

Use layout similar to (only the tiles with regular Backstage header):

https://github.com/operate-first/service-catalog/blob/main/packages/app/src/components/home/HomePage.tsx

**Comment by christophe-f** [comment]
@serenamarie125 Do you have specific training in mind?

**Comment by SamoKopecky** [comment]
I've create a PR, let me know what you think.
