### ISSUE TITLE
Add PagerDuty plugin

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#260]
### Acceptance criteria

We need to add the [PagerDuty plugin](https://github.com/backstage/backstage/tree/master/plugins/pagerduty). 

The PagerDuty card should be added to the 'Overview' tab in the Entity page and wrapped with the conditional `isPagerDutyAvailable ` flag.

**Comment by Zaperex** [comment]
So the [documentation](https://github.com/backstage/backstage/tree/master/plugins/pagerduty#custom-events-url) for the PagerDuty plugin mentions that the /pagerduty proxy endpoint will be unprotected, and then provided a method to make the plugin readOnly to restrict access to the endpoint. However, that would require them to go into the `Overview.tsx` file to make changes, would that be an issue at all if I document it in the `getting-started.md` file?

Also I just want to ask if the protected configuration should be the default configuration or should I just leave it commented out for the end user to decide?
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/cc98af80-a282-4b80-bac6-e1d7fc0529d2)

**Comment by Zaperex** [comment]
I will make a separate issue for addressing the readOnly configuration
