### ISSUE TITLE
Remove @emotion/css

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#277]
### What needs to be done?
The @emotion/css is still used in the Homepage and SearchPage.

We want to remove the following 3 dependencies, to stay consistent with Backstage:
-     "@emotion/css": "^11.11.0",
-     "@emotion/react": "^11.11.0",
-     "@emotion/styled": "^11.11.0",

**Comment by schultzp2020** [comment]
@christophe-f we cannot remove `@emotion/react` and `@emotion/styled` as they are considered peer deps. https://mui.com/material-ui/migration/migration-v4/#peer-dependencies
