### ISSUE TITLE
EZ Config: Ability to edit home page

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-showcase#340]
## Goal
_Details to follow_

### What problem does this solve?
_Details to follow_
 
### Acceptance criteria
_Details to follow_

## Requirements
- [ ] Feature
- [ ] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic
- https://github.com/janus-idp/backstage-showcase/issues/376
- https://github.com/janus-idp/backstage-showcase/issues/407 [Doc]
- https://github.com/janus-idp/backstage-showcase/issues/408 [QE]

**Comment by rtaniwa** [comment]
We actually already delivered the code for this as a rush delivery for Summit. I have liked Jai's PR. The only thing we need to track now is any QE or Doc work, which the stories are open for. So moving this to in-progress.
