### ISSUE TITLE
Database persistence for Authz policy

### ISSUE THREAD

**Issue by gorkem** [janus-idp/backstage-showcase#359]
### Acceptance criteria

Implement an Adapter that will read/write auth policy to a database. It should be possible to enable and configure this adapter through the app-config.

### Who will have access:

_Put an `x` in the boxes that apply_

- [X ] Authenticated user
- [ ] Unauthenticated user/Guest
- [ X] System Admin only

### UI/UX

All configurations should be done through app-config.

### Api documentation/information

OpenAPI link if needed

**Comment by AndrienkoAleksandr** [comment]
Draft: https://github.com/PatAKnight/backstage-plugins/pull/1

**Comment by AndrienkoAleksandr** [comment]
Pr was moved https://github.com/janus-idp/backstage-plugins/pull/544

**Comment by AndrienkoAleksandr** [comment]
I re-created pr https://github.com/janus-idp/backstage-plugins/pull/605
