### ISSUE TITLE
UI plugin for updating RBAC policy

### ISSUE THREAD

**Issue by gorkem** [janus-idp/backstage-showcase#363]
### Acceptance criteria

There should be an admin UI visible and accessible to users with permissions from #357 to update the RBAC policy. The UI should be able to map permissions to users and groups known. 

### Who will have access:

_Put an `x` in the boxes that apply_

- [X] Authenticated user
- [ ] Unauthenticated user/Guest
- [X] System Admin only

### UI/UX

TODO:

### Api documentation/information

OpenAPI link if needed

**Comment by invincibleJai** [comment]
@rtaniwa/ @kadel  does this look like a duplicate of https://github.com/janus-idp/backstage-plugins/issues/849?
