### ISSUE TITLE
Pin dependency versions using renovate

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/backstage-showcase#385]
### What needs to be done?

Update the renovate config to create less PRs so we can pin dependency versions to make the showcase image more reproducible. 

### Acceptance criteria

- Update renovate config to create less PRs
- Pin dependency versions using renovate

Creating per my discussion with @christophe-f

**Comment by christophe-f** [comment]
Updating only patch versions for now. Major and minor versions will be updated with the Backstage releases.
