### ISSUE TITLE
Some Learning Path Links are not working

### ISSUE THREAD

**Issue by mandibuswell** [janus-idp/backstage-showcase#396]
### What happened?
Some of the learning path links on the learning path cards are not working.

### What are the steps to reproduce this issue?

1. From the Showcase core navigation select Learning Paths
2. Try the following learning paths
A guided workshop for Kafka Streams
A guided workshop for Red Hat OpenShift Service Registry
A guided workshop for Red Hat OpenShift Streams for Apache Kafka
Get started with OpenShift Streams for Apache Kafka - goes to a 404 page.

I believe these learning paths are no longer available and should be removed from the learning-paths/data.json file

3. the result 
Instead of going to the guided path training, the user is directed to the https://developers.redhat.com/ page.

### Additional information
All the there other cards are working for completeness they are 
Building Operators on OpenShift
Configure a Jupyter notebook to use GPUs for AI/ML modeling
Deploy a Spring application on OpenShift
Deploy and manage your first API
Develop consumers and producers in Java
Develop with Camel K
Develop with GitOps
Developing on OpenShift
Developing OpenShift applications with Java and Quarkus
Developing with Middleware
Developing with PatternFly React
Developing with Quarkus
Developing with Spring
Event-driven architecture
Exploring OpenShift
Foundations of OpenShift
Get started with Ansible
Get started with Red Hat Enterprise Linux
How to access, download, and analyze data for S3 usage
How to create a PyTorch model
How to create a TensorFlow model
How to deploy a model using S2I
How to deploy an application using Red Hat OpenShift Service on AWS
How to get started with Intel OpenVINO
How to set up and reproduce data science experiments
Install Red Hat OpenShift Data Science in Red Hat OpenShift Service on AWS
Kafka 101
Kubernetes and friends
Launch and explore Red Hat OpenShift API Management
Mastering AI / ML with OpenShift
Red Hat OpenShift Data Science documentation and resources
Securing APIs on Red Hat OpenShift API Management
Setting up your first developer portal
Understanding subsystems
Using projects in Red Hat OpenShift Data Science

**Comment by Zaperex** [comment]
Hi thanks for pointing this out. It appears that those Learning Paths no longer exist on https://developers.redhat.com/, so we will be removing them.
