### ISSUE TITLE
Learning Path cards should be grouped logically

### ISSUE THREAD

**Issue by mandibuswell** [janus-idp/backstage-showcase#397]
### What do you want to improve?
The layout of the learning cards on the learning paths page

### What is the current behavior?
When reviewing all the learning card links to find any broken ones, it was apparent that they are listed in a rather random order. This means that for example Kafka related learning path cards are not side by side on the page but rather several cards and even several scrolls away.

If you look at the https://developers.redhat.com/learn page, the learning paths are logically grouped. ie: OpenShift learning, Data Science learning, Kakfa learning etc

### What is the new behavior?
Group the learning path cards together similarly to the developers.redhat.com/learn page. They don't have to have subpages necessarily but it would be good if all the similar learning paths were together on the page.

### :warning: Is this a breaking change?

_Put an `x` in the boxes that apply_

- [ ] Yes
- [x] No
- [ ] Don't know

**Comment by christophe-f** [comment]
Closing this issue as we can track the progress of the LMS plugin here https://github.com/janus-idp/backstage-plugins/issues/494
