### ISSUE TITLE
Duration information on the Learning Path cards

### ISSUE THREAD

**Issue by mandibuswell** [janus-idp/backstage-showcase#398]
### What do you want to improve?
When a learning path is less than 1 hour long, it should show the length instead of 0

### What is the current behavior?
the duration of learning paths is measured in hours, but if a learning path is less than 1hr say 15 minutes the duration is indicated as 0 (which is correct 0 whole hours)

### What is the new behavior?
Display the duration in minutes or a part of an hour. For example a learning path that is 15 minutes long should say Duration: 15 minutes OR Duration: .25 hours even although the former would be preferred.

### :warning: Is this a breaking change?

_Put an `x` in the boxes that apply_

- [ ] Yes
- [ ] No
- [ ] Don't know

**Comment by mandibuswell** [comment]
Here is the screen shot showing the particular learning path that is less than one hour.

<img width="895" alt="Screen Shot 2023-07-21 at 11 00 29 AM" src="https://github.com/janus-idp/backstage-showcase/assets/12392607/cdd47a2a-9c8f-49c4-a03e-ab3ce5866894">

**Comment by Zaperex** [comment]
Good point, I think it would be beneficial for us to display the time more accurately (20 minutes instead of 0 hours, 7 hours  40 minutes instead of 8 hours).
