### ISSUE TITLE
The CI tab doesn't show Tekton if GitLab is enabled.

### ISSUE THREAD

**Issue by jayfray12** [janus-idp/backstage-showcase#404]
### What happened?
The CI tab only shows `GitLab Merge Request Status` instead of the Tekton last run.  There should be a way to prioritize Tekton over GitLab if using Tekton

### What are the steps to reproduce this issue?

1. enable gitlab
2. enable tekton
3. create a component with a tekton pipeline
4. view CI tab and see message above

### Additional information

- Which devices are affected? All
- Which browsers are affected? All
- Which version are you using? RHDH 1.0

We only support the last 2 major versions.

Attach any related screenshots, if any.
![image](https://github.com/janus-idp/backstage-showcase/assets/38667521/3d46ddd5-1b20-4981-bfc1-294723b1fa36)

**Comment by tumido** [comment]
So.. it seems GitHub/GitLab plugins do not provide a way to detect if GitLab pipelines or Github actions are available separately from GitHub/GitLab VCS detection. We can't rely on this information to conditionally hide other CI content. I'll propose a fix and we can discuss with the team in a PR.
