### ISSUE TITLE
Gitlab Discovery does not work in Janus

### ISSUE THREAD

**Issue by jayfray12** [janus-idp/backstage-showcase#422]
### What happened?
The `GitlabDiscoveryEntityProvider` is not enabled for Janus.  

### What are the steps to reproduce this issue?

1. Set `GITLAB_ENABLED` to true
2. Configure the discovery by following this: https://backstage.io/docs/integrations/gitlab/discovery/
3. Observe no discovery 

### Additional information

- Which devices are affected? All
- Which browsers are affected? All
- Which version are you using? RHDH DP1

We only support the last 2 major versions.

Attach any related screenshots, if any.

**Comment by treddy08** [comment]
In addition to @jayfray12's explanation, I had to follow these instructions https://backstage.io/docs/integrations/gitlab/discovery and apply them to the latest showcase source code to get this working.  This does not work out-of-the-box with the latest showcase image.
