### ISSUE TITLE
Add the Nexus Repository Manager 3 OpenAPI spec to the catalog

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/backstage-showcase#423]
### Acceptance criteria

What are you trying to do, need? What are the acceptance criteria?

Add the Nexis Repository Manager 3 OpenAPI spec to the [catalog entities](https://github.com/janus-idp/backstage-showcase/tree/main/catalog-entities). 

### Who will have access:

_Put an `x` in the boxes that apply_

- [ ] Authenticated user
- [x] Unauthenticated user/Guest
- [ ] System Admin only

### UI/UX

N/A

### API documentation/information

https://help.sonatype.com/repomanager3/integrations/rest-and-integration-api

[nexus-swagger.zip](https://github.com/janus-idp/backstage-showcase/files/12196173/nexus-swagger.zip)

**Comment by gorkem** [comment]
Just curious what is the reason for this one?
