### ISSUE TITLE
Allow plugins to be installed dynamically, non-UI method

### ISSUE THREAD

**Issue by jasperchui** [janus-idp/backstage-showcase#446]
Epic Goal
The goal of this epic is to allow platform engineers with a method (not from the UI) to view plugins that can be installed, as well as a way to install them.

**Comment by rtaniwa** [comment]
I don't quite understand this Epic vs #442. I Jira I did close the one that maps to this one unless someone can articulate how this isn't covered under the general dynamic plugin support.

**Comment by davidfestal** [comment]
> view plugins that can be installed

Is it what makes this EPIC different from https://github.com/janus-idp/backstage-showcase/issues/442 ?

I'm not really sure I see what this means TBF, at least until we have a UI

cc @christophe-f  @gorkem @jasperchui

**Comment by rtaniwa** [comment]
I feel this issue should be closed unless someone can explain how it differs from our other dynamic plugin support epic. I already closed the Jira epic that maps to this GH issue.
