### ISSUE TITLE
Banner message should be configurable

### ISSUE THREAD

**Issue by jayfray12** [janus-idp/backstage-showcase#453]
### Describe the bug
The banner message `Welcome to Red Hat Developer Hub!` on the main screen should be configurable.  There doesn't seem to be a way to change it.

![image](https://github.com/janus-idp/backstage-showcase/assets/38667521/cbae21b1-0d93-4688-8a2e-3bf67c436c6c)

### Versions of software used and environment
RHDH DP 0.1

**Comment by tumido** [comment]
Same with showcase which is hardcoded to:
![image](https://github.com/janus-idp/backstage-showcase/assets/7453394/531f4d96-91f7-4999-a63c-6bb9599a600c)

We should parametrize this line:

https://github.com/janus-idp/backstage-showcase/blob/c798525099a59888d0ae329d69754cfc1996f77b/packages/app/src/components/home/HomePage.tsx#L85

To use `app.title` from the config or something like that. Thoughts @sonyccd @christophe-f ?

**Comment by nickboldt** [comment]
is `app.title` used in other places? Right now downstream has just "Red Hat Developer Hub" as the `app.title` https://gitlab.cee.redhat.com/rhidp/cpaas-rhdh-hub/-/blob/rhdh-1.0-rhel-9/distgit/containers/rhdh-hub/app-config.production.yaml#L3

**Comment by christophe-f** [comment]
Yes that would be great to parametize this.  Could also add input parameters such as username
