### ISSUE TITLE
Release GH action is broken - fails to generate PR because no commits found 

### ISSUE THREAD

**Issue by nickboldt** [janus-idp/backstage-showcase#455]
### What needs to be done?

```
Error: HttpError: Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between main and changeset-release/main"}
```
-- https://github.com/janus-idp/backstage-showcase/actions/runs/5968929798/job/16193781450

More failures:

https://github.com/janus-idp/backstage-showcase/actions/workflows/release.yaml

Has been failing since this commit on Aug 16 (over a week):

https://github.com/janus-idp/backstage-showcase/commit/108f6d15c1a3a9feca8b6a9e636055d883b8fc05#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR42-R48

**Comment by schultzp2020** [comment]
This is expected behavior when there are no changesets.
