### ISSUE TITLE
Build and publish ARM64 and AMD64 images

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#457]
### What needs to be done?

Build and publish ARM64 and AMD64 images

**Comment by tumido** [comment]
We can reuse build logic we've already implemented for `redhat-backstage-build` before:

https://github.com/janus-idp/redhat-backstage-build/blob/main/.github/workflows/build.yaml

**Comment by nickboldt** [comment]
Closing; will use downstream issue: https://issues.redhat.com/browse/RHIDP-1351
