### ISSUE TITLE
[Spike] Explore Backstage sidebar customisation options

### ISSUE THREAD

**Issue by divyanshiGupta** [janus-idp/backstage-showcase#464]
**Spike for** - https://issues.redhat.com/browse/RHIDP-258

**Investigate the following:**

- Are sidebar menu items icons customisable?
- Can a button (Create button) be added to the sidebar without making changes in upstream?
- Can a sidebar menu-item sub-menu be added?
- Can the expand/collapse button be placed beside a menu item?

cc: @invincibleJai @gashcrumb @debsmita1 @jerolimov

**Comment by divyanshiGupta** [comment]
Based on my exploration following are the observations:

- Menu items icon can be changed to any MUI icon that is required by the design.
```
import CatalogIcon from '@material-ui/icons/CategoryOutlined';

<SidebarItem icon={CatalogIcon} to="catalog" text="Catalog" />

```
-  Buttons can be added to the sidebar.
```
<SidebarGroup label="Create" icon={<CreateComponentIcon />} to="create">
     <Button
        color="primary"
        variant="contained"
        startIcon={<CreateComponentIcon />}
        style={{
          marginLeft: '27px',
          marginRight: '27px',
          width: '168px',
          }}
        >
          Create
      </Button>
 </SidebarGroup>
```
Currently adding buttons as menu item with icons will not work the same way as the SidebarMenuItems works with expand collapse functionality ie showing only the icons when collapsed.

- Sub menu can be added for the menu items - https://backstage.io/storybook/?path=/story/layout-sidebar--sample-scalable-sidebar
```
<SidebarItem icon={PluginsIcon} text="Plugins">
    <SidebarSubmenu title="Plugins">
           <SidebarSubmenuItem
               icon={ExtensionIcon}
               to="openshift-image-registry"
               title="Image Registry"
             />
      </SidebarSubmenu>
  </SidebarItem>
```

- Existing expand/collapse button https://backstage.io/storybook/?path=/story/layout-sidebar--sample-scalable-sidebar can be placed beside any custom menu item but after collapsing the button is not shown in case `disableExpandOnHover` is added to the Sidebar.

<img width="1791" alt="Screenshot 2023-08-28 at 8 19 19 PM" src="https://github.com/janus-idp/backstage-showcase/assets/20724543/feff35a8-4c59-44be-8396-3808ef114db2">


https://github.com/janus-idp/backstage-showcase/assets/20724543/f5f05c1c-5ba3-4e1d-aef5-c9b3a7653f90


@invincibleJai @gashcrumb @debsmita1 @jerolimov Let me know if I need to look at anything else here.

**Comment by invincibleJai** [comment]
Thanks @christophe-f for the input. Do you have insights on when this change will be available in Janus? 

Thanks @divyanshiGupta , as we discussed good to understand with Configuration can we load any custom components and  if there is some default set of components.
