### ISSUE TITLE
Add Nexus plugin to the showcase app

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#472]
### Provide a clear and concise description of the feature request

Add the [Nexus plugin](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/nexus-repository-manager) to the showcase image under the 'Image Registry' tab (or equivalent)

### Describe the problem that this feature resolves

When a user is using Nexus to publish artifacts, it will be visible in the Entity tab similar as Quay, JFrog Artifactory and Azure Registry.

**Comment by Zaperex** [comment]
Should we modify the Image Registry tab such that the Quay, Jfrog, ACR, and Nexus plugins rendering won't be mutually exclusive? The current behavior is similar to 
`if quayExists: render Quay` 
`else if JfrogExists: render JFrog` 
`else if <>Exists: render <>`

Also, [Azure registry plugin](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/acr) hasn't been installed into the showcase yet, and no issue to install it has been created yet. Are we looking to add it to the showcase?
