### ISSUE TITLE
Add a 2 weeks expiration on the published nightly builds on Quay

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#474]
### What do you want to improve?

There is a nightly build every day that will publish images to Quay. We don't need to keep these images for more than 2 weeks (14 days). We should be able to add an expiry on the nightly images.

- https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/use_red_hat_quay/working_with_tags#tag-expiration
- https://www.geeksforgeeks.org/docker-label-instruction/

### What is the current behavior?

The images never expire

### What is the new behavior?

The nightly builds will expire after 14 days.

**Comment by nemerna** [comment]
I will be happy to get assigned this issue please
