### ISSUE TITLE
Explore how to verify NPM package integrity when `npm pack`ing dynamic plugin packages

### ISSUE THREAD

**Issue by davidfestal** [janus-idp/backstage-showcase#527]

**Comment by Zaperex** [comment]
More details for the issue from discussion with @davidfestal:

- Currently the dynamic plugins can be loaded into the showcase instance using the [`install-dynamic-plugins.py` script](https://github.com/janus-idp/backstage-showcase/blob/main/docker/install-dynamic-plugins.py). 
- This script requires the user to provide a `dynamic-plugins.yaml` file that will provide the plugins in a list format
- One of the fields for each plugin in the list is a `package` field that supports local packages, packages from npm registries, and any other input that is supported by `npm pack`.
- We want to ensure that the packages being loaded are secure and that no man in the middle attack has occurred.
  - Perhaps look into verifying the integrity/sha of the package or checking signatures?

**Comment by Zaperex** [comment]
One method is to have the end-user provide the `integrity` of the package's tarball in an integrity field for each package in the `dynamic-plugins.yaml` file.

Then we can validate whether the package we pack using `npm pack` matches the integrity provided with:
`cat ./package-version.tgz | openssl dgst -sha512 -binary | openssl base64 -A`

**Comment by Zaperex** [comment]
Since this issue is just a spike/investigation, I created https://github.com/janus-idp/backstage-showcase/issues/669 to track the edits to the installation script.
