### ISSUE TITLE
Switch  static plugins in the showcase backend  to dynamic plugins

### ISSUE THREAD

**Issue by davidfestal** [janus-idp/backstage-showcase#528]
as much plugins as possible to switch in a sprint

the goal is to open PR (wip) with all the backend plugins switched and docker image available for testing.

**Comment by nickboldt** [comment]
See also https://docs.google.com/spreadsheets/d/1dNUAGTeosEzreX9fxFTW1Vq3oGCbHroZ_DFEL8sjfjY/edit#gid=0
