### ISSUE TITLE
Update the dark theme color palette to match the patternfly dark color scheme

### ISSUE THREAD

**Issue by gashcrumb** [janus-idp/backstage-showcase#535]
### What do you want to improve?
For consistency if we adopt the patternfly light color scheme, we should also adapt the patternfly dark color scheme.

Using [this configuration](https://github.com/gashcrumb/patternfly-backstage-theme/blob/main/theme/src/patternfly.ts#L90-L179) or perhaps the output of #534  as a starting point update the color scheme, [apply these changes](https://www.patternfly.org/developer-resources/dark-theme-handbook/) that make up Patternfly's dark color scheme and then finally apply this update to the dark theme.

part of #506

**Comment by jerolimov** [comment]
This ticket is resolved, all theme work is now done in the external repo https://github.com/redhat-developer/red-hat-developer-hub-theme
