### ISSUE TITLE
Apply component overrides to both dark and light themes

### ISSUE THREAD

**Issue by gashcrumb** [janus-idp/backstage-showcase#536]
### What do you want to improve?
Adopting the spacing and elements from Patternfly can go a long way to improving the look and feel as well as usability of the application.

Apply [these component overrides](https://github.com/gashcrumb/patternfly-backstage-theme/blob/main/theme/src/patternfly.ts#L181-L464) to the light theme, and take into account that some of the current overrides in this referenced file contain colors that will need to be adjusted to suit the dark theme.  Ideally most of the overrides should work for both themes, perhaps wrapping this configuration in a function where these colors could be passed in will suffice to handle the dark theme as well.

part of #506

**Comment by gashcrumb** [comment]
One addition to this outside of the theme is to ensure the home page search uses a border instead of drop shadows, [this can only be done here currently](https://github.com/janus-idp/backstage-showcase/blob/main/packages/app/src/components/home/HomePage.tsx#L25), however since the theme is passed in it should be possible to generically apply the correct corresponding color from the passed in theme.  

The border value should be something like `1px solid #d5d5d5 !important`

**Comment by jerolimov** [comment]
This ticket is resolved, all theme work is now done in the external repo https://github.com/redhat-developer/red-hat-developer-hub-theme
