### ISSUE TITLE
Integrate a code coverage tool with the PR merging process

### ISSUE THREAD

**Issue by rtaniwa** [janus-idp/backstage-showcase#544]
As part of our QE work, we need to select a code coverage tool in our CI system so that we can use it as part of our PR merging process.

**Comment by josephca** [comment]
@kadel we already have the 'SonarCloud' check for PRs, so we may close this issue if agreed.

**Comment by rnapoles-rh** [comment]
@josephca see comment from Kim in RHIDP-377
