### ISSUE TITLE
Changes in app.title are not visible

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#552]
When updating the title in the Helm config, the changes are not visible in the application

```
app:
  title: Janus Showcase
```

**Comment by Zaperex** [comment]
So for the top banner for the homepage, you want it to be `Welcome <currently logged in user via auth>?`
And you want the catalog page to change from `Janus IDP Catalog` to `<app.title> catalog`?

**Comment by kadel** [comment]
>And you want the catalog page to change from Janus IDP Catalog to <app.title> catalog?

This is already configurable from app-config.yaml by `organization.name`(<organization.name> catalog)

**Comment by Zaperex** [comment]
So what do we want to use the `app.title` for?
