### ISSUE TITLE
Update to Backstage 1.18

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/backstage-showcase#568]
### Which dependency needs to be upgraded?

Backstage

### What is the current version of the dependency?

1.17

### Which version to upgrade to?

1.18

### Changelog link

https://github.com/backstage/backstage/releases/tag/v1.18.0

**Comment by Zaperex** [comment]
@schultzp2020 there's already an existing issue for this: https://github.com/janus-idp/backstage-showcase/issues/551

**Comment by schultzp2020** [comment]
Whoops, I must've missed that.
