### ISSUE TITLE
Review RHDH E2E test scenario

### ISSUE THREAD

**Issue by rnapoles-rh** [janus-idp/backstage-showcase#597]
### What needs to be done?

Review [RHIDP-416](https://issues.redhat.com/browse/RHIDP-416) 
Scenario is available in linked document in the Jira ISSUE

Reviewer | Reviewed date
-- | --
[Tomas Kral](https://issues.redhat.com/secure/ViewProfile.jspa?name=tkral%40redhat.com)  |  2023-10-12
[Christophe Fargette](https://issues.redhat.com/secure/ViewProfile.jspa?name=jfargett%40redhat.com) |  
[Frank Kong](https://issues.redhat.com/secure/ViewProfile.jspa?name=rh-ee-frkong) |  
[Brad Bazemore](https://issues.redhat.com/secure/ViewProfile.jspa?name=bbazemor) |

**Comment by Zaperex** [comment]
Reviewed on 2023-10-12. 
Note: [RHIDP-416](https://issues.redhat.com/browse/RHIDP-416) has been closed due to completion
