### ISSUE TITLE
Add Snyk plugin

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#61]
Install and configure the Snyk plugin
https://github.com/snyk-tech-services/backstage-plugin-snyk/tree/main

Add to the 'Security Insights' tab in the entity page

**Comment by schultzp2020** [comment]
Cannot add the Snyk plugin until https://github.com/snyk-tech-services/backstage-plugin-snyk/issues/124 is fixed.

**Comment by christophe-f** [comment]
The documentation has been updated. Hopefully it fixes the 404 error.

**Comment by christophe-f** [comment]
Closing this issue for now. We can't test this plugin as we don't have access to the API for this project.
