### ISSUE TITLE
CI tab: UXD improvement

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-showcase#621]
What do you want to improve?
I would like to see all CI tools configured for service in the radio option if there are multiple instead of showing all in the same screen with scroll

Screenshots:
<img width="1200" alt="image" src="https://github.com/janus-idp/backstage-showcase/assets/5129024/d257fa61-2c82-4dee-9f68-73861d0823b9">

**Comment by christophe-f** [comment]
I don't think a component will use several CI tools.
So if the component is using Jenkins or Tekton (or others), the corresponding plugin will be displayed based on the annotation in the catalog-info yaml file.

If we go that route, it will be a huge amount of work to have all the CI plugins having the same UI.

**Comment by invincibleJai** [comment]
> I don't think a component will use several CI tools. So if the component is using Jenkins or Tekton (or others), the corresponding plugin will be displayed based on the annotation in the catalog-info yaml file.
> 
> If we go that route, it will be a huge amount of work to have all the CI plugins having the same UI.

Hi @christophe-f ideally there will be one but if `catalog-info.yaml` has multiple then now we show one after another as in below

<img width="1728" alt="image" src="https://github.com/janus-idp/backstage-showcase/assets/5129024/62111a96-2209-45f4-8805-b75a614fd3de">

and thus UX came up with this suggestion to show in radio i.e one at at time if there are multiple. Let me know if this is not valid usecase or not on prioirty 

cc @ShiranHi

**Comment by divyanshiGupta** [comment]
Unassigned myself for now as this is still under exploration if it should be implemented or not.

**Comment by invincibleJai** [comment]
Closing it for now based on the above discussions and we'll revisit if there is more ask for it.
