### ISSUE TITLE
Script for deploying multiple RHDH instances

### ISSUE THREAD

**Issue by kadel** [janus-idp/backstage-showcase#626]
For test day we will need to setup multiple RHDH instances.

It would be nice to have a script that deployed multiple RHDH instances into separate OpenShift namespaces using the setup  described in RHDH Getting Started guide.
It should not do any configuration options, just start it with the default config.

For example `./deploy-test-rhdh.sh 5` would deploy 5 RHDH instances using helm chart in namespaces `rhdh-{1..5}`

**Comment by Zaperex** [comment]
@kadel I made an initial script and put it in a github gist: https://gist.github.com/Zaperex/8c4be128dec545742272319f14727a61

**Comment by kadel** [comment]
I had to change `REPO_NAME` to `HELM_REPO_NAME` on lines [27](https://gist.github.com/Zaperex/8c4be128dec545742272319f14727a61#file-deploy-test-rhdh-sh-L27) and [30](https://gist.github.com/Zaperex/8c4be128dec545742272319f14727a61#file-deploy-test-rhdh-sh-L30) to make it work.


While testing this I realized that for test day we will have to figure out how to manage pull secret. We should not add our personal pull secrets to the cluster that multiple people will share.

**Comment by Zaperex** [comment]
@kadel Ah my bad, I updated the script to fix the typo.

As for the personal pull secrets, can we potentially create a robot account for the rhdh organization with read-only permissions and let everyone use the pull secret of the robot account instead of their own pull secrets?
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/4e573d5a-419b-4097-b2c5-f628825345d7)

**Comment by kadel** [comment]
> As for the personal pull secrets, can we potentially create a robot account for the rhdh organization with read-only permissions and let everyone use the pull secret of the robot account instead of their own pull secrets?

👍 
this could work, after test day we can just remove/invalidate the robot account to make sure that even if the secret leaks no-one can use it.
