### ISSUE TITLE
Add the Janus custom actions

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#629]
### Provide a clear and concise description of the feature request

Add the following Janus custom actions:

- kubernetes-actions
- quay-actions
- regex-actions
- service now action (https://github.com/janus-idp/backstage-plugins/issues/644)

### Describe the problem that this feature resolves

So a user can use these actions in Golden Path Templates.

**Comment by kadel** [comment]
We probably need to break this down into multiple issues (one for each action)

**Comment by christophe-f** [comment]
The custom actions have been already created in the plugins repo but were never installed in the showcase.

**Comment by kadel** [comment]
> The custom actions have been already created in the plugins repo but were never installed in the showcase. So we built them but can't use them 😄

ha, It looks like I was too quick to reply without checking the whole story 😇
