### ISSUE TITLE
Add a header in the ocm page

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#63]
The ocm page does not look like the other pages in Backstage. It's missing the header section

**Comment by SamoKopecky** [comment]
@tumido Do you think we should implement this?

**Comment by tumido** [comment]
@SamoKopecky Not necessarily. We want to have a thorough UX review on the OCM plugins first.

**Comment by christophe-f** [comment]
I know that the OCM plugin is under active development and the UX will change, but it would still be nice to have the Backstage header in the page.
` <Header title="Your Managed Clusters" />`

**Comment by SamoKopecky** [comment]
PR created to add this.
