### ISSUE TITLE
Typography overrides styles globally across the showcase application

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-showcase#633]
### Describe the bug

Currently a [static `typography`](https://github.com/janus-idp/backstage-showcase/blob/b5ba1247a48d23a1afafb47718503ef0f50aef51/packages/app/src/themes/consts.ts) is provided for the [light](https://github.com/janus-idp/backstage-showcase/blob/b5ba1247a48d23a1afafb47718503ef0f50aef51/packages/app/src/themes/lightTheme.ts#L31) and [dark](https://github.com/janus-idp/backstage-showcase/blob/b5ba1247a48d23a1afafb47718503ef0f50aef51/packages/app/src/themes/darkTheme.ts#L31) theme. This hardcoded font size is a global CSS property and causes certain text (such as the text in the techdocs) to be very small, which negatively affects the user experience.

Ex: In this [techdocs](https://github.com/janus-idp/backstage-showcase/blob/main/docs/index.md), you can barely read the text for [`Introduction`](https://github.com/janus-idp/backstage-showcase/blob/b5ba1247a48d23a1afafb47718503ef0f50aef51/docs/index.md?plain=1#L5) and [`Developer Team Guide: ...`](https://github.com/janus-idp/backstage-showcase/blob/b5ba1247a48d23a1afafb47718503ef0f50aef51/docs/index.md?plain=1#L9) and they're `h2` and `h3` headers.
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/85d656da-3e87-4a6e-b3fb-82c621518da9)
Ex: The [`h4` header](https://github.com/janus-idp/backstage-showcase/blob/b5ba1247a48d23a1afafb47718503ef0f50aef51/docs/index.md?plain=1#L71) is even less readable
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/14b5760a-d528-472c-8eab-fc13f5efcc21)

Ex: The `All Components` text is also very small
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/a38f65fc-8009-46ff-bd79-181b241eb328)

### Expected Behavior
The typography shouldn't have hardcoded font sizes

### What are the steps to reproduce this bug?

1. Open any page that shows header texts and observe that size of headers is very small and does not scale with size of normal text.

**Comment by gashcrumb** [comment]
Interesting and definitely not intended.  [Reverting this PR](https://github.com/janus-idp/backstage-showcase/pull/542) should do the trick.
