### ISSUE TITLE
Add RBAC plugin to showcase

### ISSUE THREAD

**Issue by PatAKnight** [janus-idp/backstage-showcase#698]
### Provide a clear and concise description of the feature request
Now that we have an RBAC plugin, we should add this plugin to showcase.

### Describe the problem that this feature resolves
Adds RBAC to showcase. We can create permission policies to grant access to users within showcase.

### Acceptance Criteria
- [ ] Add RBAC plugin to showcase
- [ ] Documentation on RBAC plugin within showcase

**Comment by kadel** [comment]
I believe this was done in https://github.com/janus-idp/backstage-showcase/pull/588 and https://github.com/janus-idp/backstage-showcase/pull/701.
@PatAKnight, can we close this, or is there still something missing?

**Comment by PatAKnight** [comment]
Yes, we can close this out.

Closed as completed by #588

**Comment by PatAKnight** [comment]
Yes, we can close this out.

Closed as completed by https://github.com/janus-idp/backstage-showcase/pull/588
