### ISSUE TITLE
Add OCM Plugin

### ISSUE THREAD

**Issue by PatAKnight** [janus-idp/backstage-showcase#7]
Story
- As a user, I wish to be able to view information about the clusters that I have available to me using the Open Cluster Management plugin within Backstage

Description
- The Open Cluster Management plugin allows users the ability to see information about their available clusters. Using OCM, we can view information about clusters as well as access them straight from the Backstage app.

AC
- OCM plugin added to the Backstage Showcase app
- View cluster related information within the Backstage Showcase app
- Document the OCM specific process for deployment

Additional Notes
- Will require the Kubernetes plugin to be implemented within the Backstage Showcase app

**Comment by SamoKopecky** [comment]
The OCM plugin no longer requires the Kubernetes plugin to be installed. Do you think we still need to have the k8s plugin installed?

**Comment by PatAKnight** [comment]
Thank you for the heads up about the OCM plugin. I believe we are still wanting to add the Kubernetes plugin to the showcase app as something we plan to support. The current list of plugins that we are planning to have in the showcase app can be found in [issue 69](https://github.com/janus-idp/backstage-plugins/issues/69) in the backstage-plugins repo.
