### ISSUE TITLE
Tekton plugin should be shown only on CI tab and not dedicated Tekton tab

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-showcase#718]
### Describe the bug

Tekton plugin should be shown only on CI tab and not dedicated Tekton tab if entity has annotations `janus-idp.io/tekton : <entity_name>`

### Expected Behavior 

PLR list should only be shown CI tab and not Tekton tab

### What are the steps to reproduce this bug?

1. Go to the janus-IDP instance
2. Install and configure tekton plugin 
3. add/register an entity https://github.com/invincibleJai/nationalparks-py/blob/master/catalog-info.yaml
4. Check CI tab / look for tekton tab

**Comment by invincibleJai** [comment]
with dynamic plugin this should be handled https://github.com/janus-idp/backstage-showcase/pull/700

**Comment by kadel** [comment]
task: verify that #700 fixes this

**Comment by invincibleJai** [comment]
> task: verify that #700 fixes this

No it doesn't and we need to be fixed
