### ISSUE TITLE
Update ocm, aap and Keycloak versions

### ISSUE THREAD

**Issue by kadel** [janus-idp/backstage-showcase#756]
Plugins should be upgraded to a version that includes https://github.com/janus-idp/backstage-plugins/pull/827 to make sure that users can configure the scheduler in the app-config.yaml

**Comment by Zaperex** [comment]
We're missing the 3scale plugin in our dynamic-plugins directory since it was never statically installed into the showcase at any point in time.

**Comment by kadel** [comment]
There is anotehr fix for keycloack, ocm, and app that we need to pick for the showcase:


https://github.com/janus-idp/backstage-plugins/pull/945
https://github.com/janus-idp/backstage-plugins/pull/938
