### ISSUE TITLE
rbac: inconsistent policies-csv-file's roles and policies behavior after pod restart

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [janus-idp/backstage-showcase#776]
### Describe the bug

We've implemented a predefined permissions and roles feature for the rbac-backend plugin, allowing users to specify roles and policies through an external file defined in the application configuration: permission.rbac.policies-csv-file. Currently, these roles and permissions are stored in the database, enabling admin users to modify and delete them. However, this behavior presents an inconsistency. While admin users can delete and update permissions and roles, after restarting the backstage/showcase pod, these configurations revert to the ones specified in the external file. This unexpected behavior can be confusing and frustrating for end users.

### Expected Behavior
To ensure consistent behavior, it would be beneficial to implement a mechanism disabling the update and deletion of roles originating from the permission.rbac.policies-csv-file application configuration. In this way, these roles and permissions should not be saved to the database. If the roles and permissions are sourced from an external file, they should remain exclusively stored there. Any modifications to roles or permissions should necessitate users editing the external file and providing a new version of it after restarting the pod. Enforcing this expected behavior will contribute to the stability of the feature.

### What are the steps to reproduce this bug?

1. Define some roles and permission in the external file. Defined this external file in the application configuration permission.rbac.policies-csv-file. Include this external file to the dockerfile with correct file path. Rebuild image and push.
2. Deploy showcase application.
3. Modify predefined permissions and roles using rbac-backend REST api.
4. Restart application pod (rescale deployment for example to 0 and then to 1 again).

**Comment by AndrienkoAleksandr** [comment]
Related to https://github.com/janus-idp/backstage-plugins/issues/924, but with another vision how it should be resolved

**Comment by kadel** [comment]
I've added reference to this to https://github.com/janus-idp/backstage-plugins/issues/924#issuecomment-1812574243 and closing this one to avoid duplicate issue

**Comment by rsriniva** [comment]
I am getting somewhat better consistent results when I disable rbac database - I had set it to true previously.  I suspect the RHDH container reads old config from the DB rather than parsing and overwriting the new policy in the CSV

**Comment by mbmoon** [comment]
> I am getting somewhat better consistent results when I disable rbac database - I had set it to true previously. I suspect the RHDH container reads old config from the DB rather than parsing and overwriting the new policy in the CSV

@rsriniva, can you provide example on how to disable rbac database?
