### ISSUE TITLE
Cannot install Developer Hub (CI Build)

### ISSUE THREAD

**Issue by olkornii** [janus-idp/backstage-showcase#783]
### Describe the bug

Cannot install Developer Hub (CI Build)

### What are the steps to reproduce this bug?

1. Create openshift 4.14 aws cluster
2. Add secret as described there: https://docs.google.com/document/d/1X40OGE7h0UW-nNGnkqW1ymsmgsK4zICmMuHvzFHlUzw/edit
3. login to cluster via oc
4. run "oc apply -f https://gist.githubusercontent.com/kadel/62a4ab324b32d8e81476ac38a8211430/raw/RHDH-CI.yaml" to add "Developer Hub (CI Build)" to Helm Charts
5. Select +Add -> Find "Red Hat Developer Hub (CI Build)
6. Click "Create" button -> change Root Schema/global/Enable service authe... as described here https://docs.google.com/document/d/1X40OGE7h0UW-nNGnkqW1ymsmgsK4zICmMuHvzFHlUzw/edit
7. Click "Create" button -> open "Topology" -> developer-hub has not been started
8. Open "Observ" -> Events
9. See error: "Error: container create failed: time="2023-11-15T13:36:16Z" level=error msg="runc create failed: unable to start container process: exec: \"./install-dynamic-plugins.sh\": stat ./install-dynamic-plugins.sh: no such file or directory""

### Versions of software used and environment

Red Hat Openshift 4.14.0-0.nightly-2023-11-15-031103

**Comment by kadel** [comment]
@olkornii, can you please try the latest build again? It should have been fixed now.

**Comment by olkornii** [comment]
@kadel I'll try it tomorrow once more. Thanks :)

**Comment by olkornii** [comment]
@kadel does not work for me...

**Comment by olkornii** [comment]
@kadel I had to delete bold part and now it works.
upstream:
   backstage:
      **command:
         - node
         - packages/backend**

**Comment by nickboldt** [comment]
Please update to the latest chart and try again:

https://gist.github.com/rhdh-bot/63cef5cb6285889527bd6a67c0e1c2a9 

Also in future, if you're having **RHDH specific problems** (not janus-idp/backstage-showcase), please open a JIRA to track the problem:

https://issues.redhat.com/browse/RHIDP

**Comment by olkornii** [comment]
@nickboldt I've tried with
Openshift 4.14.0
Openshift client 4.13.4-linux
Red Hat Developer Hub (CI Build) product version 1.0-186

Works for me. As I understand from discussion in Slack, error is not stable. But I'm not sure.
