### ISSUE TITLE
Create 1 OBC in janus-idp

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#79]
- [ ] Create a folder `homepage` in the bucket and move the data for the homepage
- [ ] Create a folder `techradar` in the bucket and move the data for the techradar page

We could also create a GPT for this feature. https://github.com/janus-idp/software-templates/issues/88

**Comment by PatAKnight** [comment]
With the feature [fetch customization data from remote](https://github.com/janus-idp/backstage-showcase/pull/351) being merged, I am going to put this on hold. The original work was to attempt to read the homepage and tech radar data from an S3 bucket. The previously mentioned PR does that without the need for an S3 bucket making it more versatile. 

Also, we are no longer using an OBC with the showcase app. Which means that this could probably be closed if we decide to drop the [read external data from s3](https://github.com/janus-idp/backstage-showcase/pull/312) PR

**Comment by PatAKnight** [comment]
Closing this as we already have a mechanism for reading external data for the homepage and techradar
