### ISSUE TITLE
feat: Tokens for use with the REST API

### ISSUE THREAD

**Issue by jesuino** [janus-idp/backstage-showcase#811]
### Provide a clear and concise description of the feature request

As user I want to interact with the REST APIs from my third part application, but currently it is not possible to generate a token from UI or from other endpoint.

The backstage UI sends a bearer token for all API requests, but users currently can't do it without inspecting requests from Backstage UI:

![image](https://github.com/janus-idp/backstage-showcase/assets/359820/832fb383-9c61-41b4-a997-1a9367b6ce8b)

### Describe the problem that this feature resolves

Allow third part applications to consume backstage REST API. 

### Acceptance Criteria
A documented endpoint or UI screen should allow users to generate tokens that can be used with the REST API.

**Comment by jesuino** [comment]
Related documentation:

https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md

**Comment by nickboldt** [comment]
@jesuino can you open this as a feature request against backstage/backstage ? this would need to land there.

**Comment by jesuino** [comment]
@nickboldt Thanks for your comment.

After a few months I do believe that a feasible solution would use the authentication provider to issue tokens for the caller.   Having this in mind, a documentation explaining how to achieve it using some of the supported providers could be the solution for this specific issue (token for RBAC API).

Hence I am going ahead and closing this issue.

**Comment by jesuino** [comment]
Just leaving a comment for others to check. This could be the solution for this: https://backstage.io/docs/auth/service-to-service-auth/#static-tokens
