### ISSUE TITLE
[Doc] duplicated Wrapping a third-party plugin sections on Dynamic Plugins support doc

### ISSUE THREAD

**Issue by josephca** [janus-idp/backstage-showcase#821]
### What do you want to improve?
In the [Dynamic Plugins support](https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/dynamic-plugins.md) doc, minor cosmetic issue needs to be addressed. 

1. merge duplicate appearance of `Wrapping a third-party plugin to add dynamic plugin support`
  - [appearance 1](https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/dynamic-plugins.md#wrapping-a-third-party-plugin-to-add-dynamic-plugin-support)
  - [appearance 2](https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/dynamic-plugins.md#wrapping-a-third-party-plugin-to-add-dynamic-plugin-support-1)

2. to avoid any confusion no numbering is needed  for a single bullet point: https://github.com/janus-idp/backstage-showcase/blob/44e006333e001e7a990ff439957d81b82179f58d/showcase-docs/dynamic-plugins.md?plain=1#L229

**Comment by Zaperex** [comment]
I believe for the `Wrapping a third-party plugin to add dynamic plugin support` sections, one is for frontend dynamic plugins and one is for backend dynamic plugins as they have slightly different wrapping processes.
