### ISSUE TITLE
Demo site inaccessible

### ISSUE THREAD

**Issue by almereyda** [janus-idp/backstage-showcase#839]
### Describe the bug

Opening https://showcase.janus-idp.io/ is currently not possible.

### Expected Behavior

It is possible to have a look at the showcase at https://showcase.janus-idp.io/ where one sees how it integrates the various plugins.

### What are the steps to reproduce this bug?

1. Enter https://showcase.janus-idp.io/ into the URL bar of a browser.

**Comment by kadel** [comment]
@almereyda can you please add more details, like what errors you are getting? 

https://showcase.janus-idp.io/ is working ok for me

**Comment by kadel** [comment]
I'm closing this issues as the showcase seems to be working fine. 
@almereyda feel free to reopen, or ping me if you are still having issues

**Comment by almereyda** [comment]
Maybe it was a local network condition. Sorry for the confusion.
