### ISSUE TITLE
Add logging statements to scalprum-backend to log dynamic frontend plugins as well.

### ISSUE THREAD

**Issue by gashcrumb** [janus-idp/backstage-showcase#893]
### What do you want to improve?

It'd be good if the frontend plugnis loaded were also logged just like the backend plugins, so that a user doesn't have to look in two places.

### What is the current behavior?

Currently loaded backend plugins are logged to stdout, however frontend plugins are not, and the way to see that is by using the rest API once the app is initialized.

### What is the new behavior?

We could have the scalprum plugin log what it discovers as well, which could look something like the second block of logging output in this screenshot:

![image](https://github.com/janus-idp/backstage-showcase/assets/351660/de8668f8-e39e-4df8-96f0-0d910d8589a4)

@davidfestal do you think this would be worthwhile in the short term?

**Comment by davidfestal** [comment]
> @davidfestal do you think this would be worthwhile in the short term?

Yes, I think it can be useful.
