### ISSUE TITLE
Fail the build if the yarn.lock file is changed after running yarn install

### ISSUE THREAD

**Issue by gashcrumb** [janus-idp/backstage-showcase#949]
### What do you want to improve?

Often when running yarn install after updating the `yarn.lock` file contains changes.

### What is the current behavior?

This is not ideal as it means there's inconsistencies between what folks are committing and what is being tested in github actions.

### What will the new behavior be?

The build action will fail if there's changes to the `yarn.lock` file after running `yarn install`

See [this comment](https://github.com/janus-idp/backstage-plugins/pull/1143#issuecomment-1916880791) for more information:

Yes this is a copy of https://github.com/janus-idp/backstage-plugins/issues/1169

**Comment by nickboldt** [comment]
See https://issues.redhat.com//browse/RHIDP-1204 for updates.

PRs for this:
* https://github.com/janus-idp/backstage-showcase/pull/1175 (1.1.x)
* https://github.com/janus-idp/backstage-showcase/pull/1174 (main)

**Comment by gashcrumb** [comment]
I think not to be honest.  For me it's a red flag that there's something going on that needs to be investigated.  Or it indicates that an upgrade has migrated the configuration files, in which case I think that this kind of change to the files should be required to be included in a PR update as well.

**Comment by nickboldt** [comment]
so you're saying this is a GOOD and EXPECTED failure, and the change proposed by this PR is approved?

**Comment by gashcrumb** [comment]
I take that back after looking at the PR action :smile: .  Turns out the PR check build is copying the app config into place for some reason, so we should leave those two changed files as-is for now and just focus on the `yarn.lock`.

**Comment by nickboldt** [comment]
Woo! Snyk PRs are now failing with

```
After 'yarn install', workspace is dirty! The following files have changed:

app-config.example.yaml
app-config.yaml
yarn.lock
```

https://github.com/janus-idp/backstage-showcase/actions/runs/8661941105/job/23752905502?pr=1104
