### ISSUE TITLE
Fix security issue from Quay report

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#99]
Fix the following security issue:

https://quay.io/repository/janus-idp/backstage-showcase/manifest/sha256:692660768d9158f4f4a55da7da6aa6ec6eb69906b503a32d580cbcd7230150ff?tab=vulnerabilities&fixable=true

**Comment by schultzp2020** [comment]
We cannot fix the issue directly. We have to wait until RH updates the base image.
